# Movies API and DB playgrouns

## Abstract
This repository contains four application. 
The aim of creation was to get familiar how works REST and SOAP api and also SQL and NoSQL databases. 
In current direcory you can find four repository.
- REST API with NoSQL database (Spring, MongoDB),
- REST API with SQL database (Spring, MySQL),
- SOAP API with NoSQL database (Spring, MySQL)
To read about installation process and how deal with these application read a documentation in application directory.