//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.18 at 09:55:34 AM CEST 
//


package com.cinemasevice.soapwebservicesproducing;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cinemasevice.soapwebservicesproducing package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cinemasevice.soapwebservicesproducing
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMovieByTitleRequest }
     * 
     */
    public GetMovieByTitleRequest createGetMovieByTitleRequest() {
        return new GetMovieByTitleRequest();
    }

    /**
     * Create an instance of {@link GetMovieByIdRequest }
     * 
     */
    public GetMovieByIdRequest createGetMovieByIdRequest() {
        return new GetMovieByIdRequest();
    }

    /**
     * Create an instance of {@link GetMovieResponse }
     * 
     */
    public GetMovieResponse createGetMovieResponse() {
        return new GetMovieResponse();
    }

    /**
     * Create an instance of {@link Movie }
     * 
     */
    public Movie createMovie() {
        return new Movie();
    }

    /**
     * Create an instance of {@link GetAllMovieRequest }
     * 
     */
    public GetAllMovieRequest createGetAllMovieRequest() {
        return new GetAllMovieRequest();
    }

    /**
     * Create an instance of {@link GetAllMovieResponse }
     * 
     */
    public GetAllMovieResponse createGetAllMovieResponse() {
        return new GetAllMovieResponse();
    }

    /**
     * Create an instance of {@link AddMovieRequest }
     * 
     */
    public AddMovieRequest createAddMovieRequest() {
        return new AddMovieRequest();
    }

    /**
     * Create an instance of {@link EditMovieRequest }
     * 
     */
    public EditMovieRequest createEditMovieRequest() {
        return new EditMovieRequest();
    }

    /**
     * Create an instance of {@link DeleteMovieByIdRequest }
     * 
     */
    public DeleteMovieByIdRequest createDeleteMovieByIdRequest() {
        return new DeleteMovieByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteMovieByTitleRequest }
     * 
     */
    public DeleteMovieByTitleRequest createDeleteMovieByTitleRequest() {
        return new DeleteMovieByTitleRequest();
    }

    /**
     * Create an instance of {@link DeleteAllMoviesRequest }
     * 
     */
    public DeleteAllMoviesRequest createDeleteAllMoviesRequest() {
        return new DeleteAllMoviesRequest();
    }

    /**
     * Create an instance of {@link StatusResponse }
     * 
     */
    public StatusResponse createStatusResponse() {
        return new StatusResponse();
    }

}
