//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.18 at 09:55:34 AM CEST 
//


package com.cinemasevice.soapwebservicesproducing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="titleType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="primaryTitle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="originalTitle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="isAdult" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="startYear" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="endYear" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="runtimeMinutes" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="genres" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "titleType",
    "primaryTitle",
    "originalTitle",
    "isAdult",
    "startYear",
    "endYear",
    "runtimeMinutes",
    "genres"
})
@XmlRootElement(name = "editMovieRequest")
public class EditMovieRequest {

    protected long id;
    @XmlElement(required = true)
    protected String titleType;
    @XmlElement(required = true)
    protected String primaryTitle;
    @XmlElement(required = true)
    protected String originalTitle;
    protected boolean isAdult;
    protected short startYear;
    protected short endYear;
    protected int runtimeMinutes;
    @XmlElement(required = true)
    protected String genres;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the titleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleType() {
        return titleType;
    }

    /**
     * Sets the value of the titleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleType(String value) {
        this.titleType = value;
    }

    /**
     * Gets the value of the primaryTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryTitle() {
        return primaryTitle;
    }

    /**
     * Sets the value of the primaryTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryTitle(String value) {
        this.primaryTitle = value;
    }

    /**
     * Gets the value of the originalTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalTitle() {
        return originalTitle;
    }

    /**
     * Sets the value of the originalTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalTitle(String value) {
        this.originalTitle = value;
    }

    /**
     * Gets the value of the isAdult property.
     * 
     */
    public boolean isIsAdult() {
        return isAdult;
    }

    /**
     * Sets the value of the isAdult property.
     * 
     */
    public void setIsAdult(boolean value) {
        this.isAdult = value;
    }

    /**
     * Gets the value of the startYear property.
     * 
     */
    public short getStartYear() {
        return startYear;
    }

    /**
     * Sets the value of the startYear property.
     * 
     */
    public void setStartYear(short value) {
        this.startYear = value;
    }

    /**
     * Gets the value of the endYear property.
     * 
     */
    public short getEndYear() {
        return endYear;
    }

    /**
     * Sets the value of the endYear property.
     * 
     */
    public void setEndYear(short value) {
        this.endYear = value;
    }

    /**
     * Gets the value of the runtimeMinutes property.
     * 
     */
    public int getRuntimeMinutes() {
        return runtimeMinutes;
    }

    /**
     * Sets the value of the runtimeMinutes property.
     * 
     */
    public void setRuntimeMinutes(int value) {
        this.runtimeMinutes = value;
    }

    /**
     * Gets the value of the genres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenres() {
        return genres;
    }

    /**
     * Sets the value of the genres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenres(String value) {
        this.genres = value;
    }

}
